use S¹d;
CREATE TABLE SPECJALIZACJE
(
	ID_Specjalizacji INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nazwa VARCHAR(50) NOT NULL UNIQUE,
);

CREATE TABLE TYPY_PE£NOMOCNICTWA
(
	ID_Typu INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nazwa VARCHAR(50) NOT NULL UNIQUE,
);

CREATE TABLE RODZAJE_PE£NOMOCNICTWA
(
	ID_Rodzaju INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nazwa VARCHAR(50) NOT NULL UNIQUE,
);

CREATE TABLE OSOBY 
(
	ID_Osoby INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Imie VARCHAR(30) NOT NULL,
	Nazwisko VARCHAR(30) NOT NULL,
	PESEL VARCHAR(11) NOT NULL UNIQUE,
	Data_urodzenia DATE NOT NULL,	

	CONSTRAINT CK_PESEL_Osoby CHECK (dbo.IsValidPesel(PESEL) = 1),
	CONSTRAINT CK_Data_urodzenia CHECK (CAST(Data_urodzenia AS DATE) <= CAST(GETDATE() AS DATE))
);

CREATE TABLE MAGISTROWIE_NAUK_PRAWNICZYCH 
(
	Numer_dyplomu INT NOT NULL PRIMARY KEY,
	Uczelnia VARCHAR(100) NOT NULL,
	Data_uzyskania DATE NOT NULL,	
	Specjalizacja INT REFERENCES Specjalizacje(ID_Specjalizacji) ON UPDATE CASCADE ON DELETE SET NULL,
	Liczba_spraw INT NOT NULL,
	
	CONSTRAINT CK_Data_uzyskania CHECK (CAST(Data_uzyskania AS DATE) <= CAST(GETDATE() AS DATE))
);

CREATE TABLE ADWOKACI 
(
	ID_Adwokata INT NOT NULL PRIMARY KEY REFERENCES OSOBY(ID_Osoby) ON DELETE CASCADE ON UPDATE CASCADE,
	Nr_wpisu_karty_adwokackiej INT NOT NULL UNIQUE,
	Data_wydania_karty_adwokackiej DATE NOT NULL UNIQUE,
	Numer_dyplomu INT NOT NULL REFERENCES MAGISTROWIE_NAUK_PRAWNICZYCH(Numer_dyplomu) ON DELETE CASCADE ON UPDATE CASCADE,

	CONSTRAINT CK_Data_wydania_karty_adwokackiej CHECK (CAST(Data_wydania_karty_adwokackiej AS DATE) <= CAST(GETDATE() AS DATE))

);

CREATE TABLE SPRAWY 
(
	Sygnatura VARCHAR(30) NOT NULL PRIMARY KEY,
	Data_wniesienia DATE NOT NULL,
	Data_przyjêcia DATE,
	Opis_sprawy VARCHAR(MAX) NOT NULL,
	Status_sprawy VARCHAR(50) NOT NULL,
	Rodzaj_postêpowania VARCHAR(50),
	Wyrok VARCHAR(200),
	Data_rozpoczêcia DATE,
	Data_zakoñczenia DATE,
	Liczba_rozpraw INT DEFAULT 0,
	Poufne BIT,
	Dowody VARCHAR(MAX),
	Wyrok_prawomocny BIT,

	CONSTRAINT CK_Data_wniesienia CHECK (CAST(Data_wniesienia AS DATE) <= CAST(GETDATE() AS DATE)),
	CONSTRAINT CK_Data_przyjêcia CHECK (Data_przyjêcia >= Data_wniesienia),
	CONSTRAINT CK_Data_rozpoczêcia CHECK (Data_rozpoczêcia >= Data_przyjêcia),
	CONSTRAINT CK_Data_zakoñczenia CHECK (Data_zakoñczenia >= Data_rozpoczêcia),

);


CREATE TABLE ZEZNAJE
(
	ID_Zeznawania INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_Œwiadka INT NOT NULL REFERENCES OSOBY(ID_Osoby) ON DELETE CASCADE ON UPDATE CASCADE,
	Sygnatura_sprawy VARCHAR(30) NOT NULL REFERENCES SPRAWY(Sygnatura) ON DELETE CASCADE ON UPDATE CASCADE,
	Powi¹zanie VARCHAR(1000) NOT NULL,
	Data_zeznañ DATE

);
CREATE TABLE ROZPOCZYNA
(
	ID_Rozpoczynania INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_Powoda INT NOT NULL REFERENCES OSOBY(ID_Osoby) ON DELETE CASCADE ON UPDATE CASCADE,
	Sygnatura_sprawy VARCHAR(30) NOT NULL REFERENCES SPRAWY(Sygnatura) ON DELETE CASCADE ON UPDATE CASCADE,
	Rodzaj_powoda VARCHAR(30) NOT NULL
);
CREATE TABLE BRONI_SIÊ_W 
(
	ID_Bronienia_siê INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_Pozwanego INT NOT NULL REFERENCES OSOBY(ID_Osoby) ON DELETE CASCADE ON UPDATE CASCADE,
	Sygnatura_sprawy VARCHAR(30) NOT NULL REFERENCES SPRAWY(Sygnatura) ON DELETE CASCADE ON UPDATE CASCADE,
	Areszt_tymczasowy BIT NOT NULL, 
	Ma³oletni AS dbo.checkMaloletni(ID_Pozwanego),
);
CREATE TABLE PROKURATORZY
(
	ID_Prokuratora INT NOT NULL REFERENCES OSOBY(ID_Osoby) ON DELETE CASCADE ON UPDATE CASCADE,
	Data_mianowania DATE NOT NULL,
	Data_zakoñczenia DATE,
	Numer_dyplomu INT NOT NULL REFERENCES MAGISTROWIE_NAUK_PRAWNICZYCH(Numer_dyplomu) ON DELETE CASCADE ON UPDATE CASCADE,

	CONSTRAINT CK_Data_mianowania_P CHECK (CAST(Data_mianowania AS DATE) < CAST(GETDATE() AS DATE))

);
CREATE TABLE PE£NOMOCNICY
(
	ID_Pe³nomocnienia INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_Pe³nomocnika INT NOT NULL REFERENCES OSOBY(ID_Osoby) ON DELETE CASCADE ON UPDATE CASCADE,
	Rodzaj_pe³nomocnictwa INT REFERENCES RODZAJE_PE£NOMOCNICTWA(ID_Rodzaju) ON DELETE SET NULL ON UPDATE CASCADE,
	Typ_pe³nomocnika INT REFERENCES TYPY_PE£NOMOCNICTWA(ID_Typu) ON DELETE SET NULL ON UPDATE CASCADE,
	ID_Rozpoczynajacego INT REFERENCES ROZPOCZYNA(ID_Rozpoczynania) ON DELETE NO ACTION ON UPDATE NO ACTION,
	ID_Broniacego_sie INT REFERENCES BRONI_SIÊ_W(ID_Bronienia_siê) ON DELETE NO ACTION ON UPDATE NO ACTION,

	 CONSTRAINT Check_Powod_Pozwany 
        CHECK (
            (ID_Rozpoczynajacego IS NOT NULL AND ID_Broniacego_sie IS NULL) OR
            (ID_Rozpoczynajacego IS NULL AND ID_Broniacego_sie IS NOT NULL)
        ),


);

CREATE TABLE WYDZIA£Y
(
	Nazwa VARCHAR(100) NOT NULL PRIMARY KEY,
	Kierownik VARCHAR(50) NOT NULL
);
CREATE TABLE SÊDZIOWIE
(
	ID_Sêdziego INT NOT NULL PRIMARY KEY REFERENCES OSOBY(ID_Osoby) ON DELETE CASCADE ON UPDATE CASCADE,
	Numer_dyplomu INT NOT NULL REFERENCES MAGISTROWIE_NAUK_PRAWNICZYCH(Numer_dyplomu) ON DELETE CASCADE ON UPDATE CASCADE,
	Data_mianowania DATE NOT NULL,
	Data_zakoñczenia DATE,
	Wydzia³ varchar(100) REFERENCES WYDZIA£Y(Nazwa) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT CK_Data_mianowania_S CHECK (CAST(Data_mianowania AS DATE) < CAST(GETDATE() AS DATE))
);
CREATE TABLE SÊDZIOWIE_SPRAWY 
(
    ID_Sêdziego INT NOT NULL,
    Sygnatura_sprawy VARCHAR(30) NOT NULL,
    
    PRIMARY KEY (ID_Sêdziego, Sygnatura_sprawy),
    
    FOREIGN KEY (ID_Sêdziego) REFERENCES SÊDZIOWIE(ID_Sêdziego) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (Sygnatura_sprawy) REFERENCES SPRAWY(Sygnatura) ON DELETE CASCADE ON UPDATE CASCADE
);