use S¹d
DROP TABLE ADWOKACI
DROP TABLE PE£NOMOCNICY
DROP TABLE BRONI_SIÊ_W
DROP TABLE PROKURATORZY
DROP TABLE ROZPOCZYNA
DROP TABLE SÊDZIOWIE_SPRAWY
DROP TABLE SÊDZIOWIE
DROP TABLE WYDZIA£Y
DROP TABLE ZEZNAJE
DROP TABLE SPRAWY
DROP TABLE MAGISTROWIE_NAUK_PRAWNICZYCH
DROP TABLE SPECJALIZACJE
DROP TABLE TYPY_PE£NOMOCNICTWA
DROP TABLE RODZAJE_PE£NOMOCNICTWA
DROP TABLE OSOBY
